version: "3.9"

services:

  db:
    image: postgres:11
    container_name: pgvector3
    ports:
      - "5431:5432"
    env_file:
      - env
    volumes:
      - /tmp/postgresql:/data/postgres
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
    name: my_network